version: '2'

services:
    web:
        image: lavoweb/php-5.6
        ports:
            - "80:80"
        volumes:
            - ./:/var/www/html
        links:
            - db:db
    db:
        image: mysql:5.7
        ports:
            - "3306:3306"
        environment:
            - MYSQL_DATABASE=camagru
            - MYSQL_USER=camagru
            - MYSQL_PASSWORD=camagru42
            - MYSQL_ROOT=root
            - MYSQL_ROOT_PASSWORD=root42
    myadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8080:80"
        links:
            - db:db
    mail:
        image: tvial/docker-mailserver:latest
        hostname: mail
        domainname: domain.com
        container_name: mail
        ports:
            - "25:25"
            - "143:143"
            - "587:587"
            - "993:993"
        volumes:
            - maildata:/var/mail
            - mailstate:/var/mail-state
            - maillogs:/var/log/mail
            - ./config/:/tmp/docker-mailserver/
        environment:
            - ENABLE_SPAMASSASSIN=1
            - ENABLE_CLAMAV=1
            - ENABLE_FAIL2BAN=1
            - ENABLE_POSTGREY=1
            - ONE_DIR=1
            - DMS_DEBUG=0
        cap_add:
            - NET_ADMIN
            - SYS_PTRACE

volumes:
  maildata:
    driver: local
  mailstate:
    driver: local
  maillogs:
    driver: local


# docker-machine create server
# eval $(docker-machine env server)
# docker-compose up