version: '2'

services:
	web:
		image: lavoweb/php-5.6
		ports:
			- "80:80"
		volumes:
			- ./:/var/www/html
		links:
			- db:db
	db:
		image: mysql:5.7
		ports:
			- "3306:3306"
		environment:
			- MYSQL_DATABASE=camagru
			- MYSQL_USER=camagru
			- MYSQL_PASSWORD=camagru42
			- MYSQL_ROOT=root
			- MYSQL_ROOT_PASSWORD=root42
	myadmin:
		image: phpmyadmin/phpmyadmin
		ports:
			- "8080:80"
		links:
			- db:db
	# mailhog:
	#   image: mailhog/mailhog:v1.0.0
	#   ports:
	# 	- "1025:1025"
	# 	- "8025:8025"


# docker-machine create server
# eval $(docker-machine env server)
# docker-compose up